//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUVCServiceAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.LocationEquipment = new HashSet<LocationEquipment>();
            this.Requests = new HashSet<Requests>();
        }
    
        public int ID { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentDescription { get; set; }
        public int IDOwnerEquipment { get; set; }
        public int IDLocation { get; set; }
        public Nullable<int> IDSpare { get; set; }
        public int IDStatus { get; set; }
    
        public virtual SparesEquipment SparesEquipment { get; set; }
        public virtual StatusEquipment StatusEquipment { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationEquipment> LocationEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
