//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUVCServiceAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationEquipment
    {
        public int ID { get; set; }
        public int IDEquipment { get; set; }
        public string Floor { get; set; }
        public string Auditorium { get; set; }
        public string Building { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
