//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUVCServiceAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryPrograms
    {
        public int ID { get; set; }
        public int IDSpecialization { get; set; }
        public string NameProgram { get; set; }
        public string VersionProgram { get; set; }
        public string DescriptionProgram { get; set; }
    
        public virtual Specialization Specialization { get; set; }
    }
}
