//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUVCServiceAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreateRequest { get; set; }
        public Nullable<System.DateTime> DateExecuteRequest { get; set; }
        public int IDUserRequest { get; set; }
        public Nullable<int> IDExecutorRequest { get; set; }
        public int IDEquipment { get; set; }
        public int IDStatus { get; set; }
        public int IDPriority { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual PriorityRequest PriorityRequest { get; set; }
        public virtual StatusRequest StatusRequest { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
